### PR TITLE
New settings parser - Issue at https://issues.civicrm.org/jira/browse/CRM-16418

### PR DESCRIPTION
**Pull request by JoshuaKissoon**
Parser
- Created a parser for .settings.php file
-- Parser simply extends the php parser since setting files are PHP files

Extract Command
Updated the ExtractCommand.php file to include the new settings parser and use it for parsing .setting.php files

Tests
- Added a sample setting file from civicrm, updated it with a few ts() calls
- Sample output is included

---

 * [CRM-16418: Localization of settings metadata](https://issues.civicrm.org/jira/browse/CRM-16418)

### CODE REVIEW

**Comment by totten** [comment]
Thank you. This looks nicely done.

One missing thing: to include the new examples as part of the test, it needs an update to `ExtractCommandTest::examples()`:

https://github.com/civicrm/civistrings/blob/master/tests/Command/ExtractCommandTest.php#L13

**Comment by totten** [comment]
(If you get a chance to do that and push it, please ping me the discussion thread. Github does not automatically send notices about updates.)

**Comment by JoshuaKissoon** [comment]
Hey @totten I've made the updates

**Comment by totten** [comment]
@JoshuaKissoon, nice. :) I merged it and will update buildkit to include the changes.

Aside: To get `phpunit` passing, I made one small change while merging (0ee82521b55).

**Pull request merged**
